services:
  labelsdb-editor:
    image: nginx:alpine
    container_name: labelsdb-editor
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "4377:80"
